server:
  port: 8081
  shutdown: GRACEFUL

spring:
  application:
    name: peer-to-peer

  jackson:
    default-property-inclusion: non_null

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:postgresql://localhost:5432/peer-to-peer
    username: postgres
    password: postgres
    hikari:
      connection-test-query: SELECT 1
      leak-detection-threshold: 5000
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show-sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: c1f94d0ba56483d23f1e819b4494db88562e506ca382c8fdf074e0fdf074cd18
  expiration: 86400000

application:
  filepath: /Users/user/Downloads/peer-to-peer/src/main/resources/files/

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true