server:
  shutdown: GRACEFUL

spring:
  application:
    name: peer-to-peer

  jackson:
    default-property-inclusion: non_null

  lifecycle:
    timeout-per-shutdown-phase: 30s

  datasource:
    url: jdbc:postgresql://localhost:5432/peer-to-peer
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show-sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: OUoMJuR/GQzbF/nZhbceKconN9h/I2jnA0kf5jD5f4k=OxJiZcjkbUuQMcBNfNOxlXFikrqm6v3gfVmUvSceoHQ=
  expiration: 86400000