server:
  shutdown: GRACEFUL

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    redis:
      url: redis://localhost:6379
  application:
    name: peer-to-peer
  datasource:
    url: jdbc:postgresql://localhost:5432/peer-to-peer
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  #  liquibase:
  #    enabled: true
  #    change-log: classpath:db.changelog/db.changelog.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        show-sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
